clients:
  default:
    blocked: false
    limit: 10000000
    models: '*'
  pylibs:
    blocked: false
    limit: 10000000
    models: '*'
  testmanager:
    blocked: false
    limit: 10000000
    models: '*'
  cassandra:
    blocked: false
    limit: 10000000
    models: '*'
  comic-generator:
    blocked: false
    limit: 10000000
    models: '*'
  baselinevulnboard:
    blocked: false
    limit: 10000000
    models: '*'
  cyberpulse:
    blocked: false
    limit: 10000000
    models: '*'
  domainstats:
    blocked: false
    limit: 10000000
    models: '*'
  zscaler_bypass:
    blocked: false
    limit: 10000000
    models: '*'
  neurotracker:
    blocked: false
    limit: 10000000
    models: '*'
  storygen:
    blocked: false
    limit: 10000000
    models: '*'
  soc-panic:
    blocked: false
    limit: 10000000
    models: '*'
  yads-testing:
    blocked: false
    limit: 10000000
    models: '*'
  comicmakerng:
    blocked: false
    limit: 10000000
    models: '*'
  llmgui:
    blocked: false
    limit: 10000000
    models: '*'
  hermes:
    blocked: false
    limit: -1
    models: '*'
